#    <center> <b> <span style="color:orange;" >  `33 Days of Parallel reading` </span> </b></center>


## <center> <b> <span style="color:orange;"> An initiation to Machine Learning </span> </b></center>

### <center> <b> <span style="color:blue;"> A comprehensive guide to Numpy for Data manipulation </span> </b></center>




#### Author: [Yaé Ulrich Gaba](https://github.com/gabayae)

#### Link to the notebook on the repo: [A comprehensive guide to Numpy](https://github.com/gabayae/-66DaysOfData-KennethJee/edit/main/README.md)

## ToC 

- [NumPy](#NumPy)  
  - [Overview](#Overview)  
  - [Getting Started](#Getting-Started)
    - [Load packages](#Load-packages)
    - [Introduction to Numpy](Introduction-to-Numpy)
  - [NumPy Arrays](#NumPy-Arrays) 
    - [NumPy Arrays from Python Lists](#NumPy-Arrays-from-Python-Lists)
    - [NumPy Arrays using the function arange()](#NumPy-Arrays-using-the-function-arange())
    - [NumPy Arrays using the function linspace()](#NumPy-Arrays-using-the-function-linspace())
    - [NumPy Array Attributes](#NumPy-Array-Attributes)
    - [Some Numpy Special Arrays](#Some-Numpy-Special-Arrays)
    - [NumPy Arrays using the function empty()](#NumPy-Arrays-using-the-function-empty())
  - [Operations on Arrays](#Operations-on-Arrays)
    - [Array Concatenation and Splitting](#Array-Concatenation-and-Splitting)
    - [Numpy Arrays Universal Functions](NumPy-Arrays-Universal-Functions) 

## Overview


Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas ([next lesson]()) are built around the NumPy array. This notebook will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays. Get to know them well!

[NumPy](https://en.wikipedia.org/wiki/NumPy) (pronounced /ˈnʌmpaɪ/ (NUM-py) or sometimes /ˈnʌmpi/ (NUM-pee)) is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

[NumPy](https://en.wikipedia.org/wiki/NumPy) is a first-rate library for numerical programming

- Widely used in academia, finance and industry.  
- Mature, fast, stable and under continuous development.  

## Getting Started

### Load packages

In order to be able to use numpy we need to import the library using the special word `import`. Also, to avoid typing `numpy` every time we want to use one if its functions we can provide an alias using the special word `as`:

In [32]:
import numpy as np

### Introduction to Numpy

Now, we have access to all the functions available in `numpy` by typing `np.name_of_function`. For example, the equivalent of `1 + 1` in Python can be done in `numpy`:

In [33]:
np.add(1,1)

2

Although this might not at first seem very useful, even simple operations like this one can be much quicker in `numpy` than in standard Python when using lots of numbers (large arrays).

To access the documentation explaining how a function is used, its input parameters and output format we can press `Shift+Tab` after the function name. Try this in the cell below

In [34]:
np.add

<ufunc 'add'>

## NumPy Arrays

The core concept in numpy is the `array` which is equivalent to lists of numbers but can be multidimensional. 
The essential problem that NumPy solves is fast array processing. The most important structure that NumPy defines is an array data type formally called a [numpy.ndarray](http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html). NumPy arrays power a large proportion of the scientific Python ecosystem. Let us list ways of creating Numpy arrays one by one, with Examples.




### NumPy Arrays from Python Lists

In [35]:
# making a python list li
li = [8,5,6,9,4,2]


# creating array out of it
numpy_array_from_list = np.array(li)

# printing the array
print(numpy_array_from_list)


[8 5 6 9 4 2]


In [36]:
# checking the type of numpy_array_from_list
type(numpy_array_from_list)

numpy.ndarray

We can also pass a list manually without explicitly defining it.

In [37]:
numpy_array_from_list1 = np.array([5,7,4,1,5,6])
print(numpy_array_from_list1)

[5 7 4 1 5 6]


In [38]:
type(numpy_array_from_list1)

numpy.ndarray

Other arguments which are optional can also be included while creating the Numpy arrays. One of the optional parameter, that you might find useful is:

<b> <span style="color:brown;" >  dtype </span> </b>: This argument specifies the data-type of the array being created. Since, unlike lists, all the elements in the Numpy array are of the same data-type. The datatypes ranging from float to complex, all are acceptable.

Let us see with an example:

In [39]:
numpy_array_float = np.array([1,8,5,59,8,98], dtype = 'float')
print(numpy_array_float)


print("======================================")

# let's try Numpy array with string as input
str = ['the','air','after','summer','rain']
numpy_array_str = np.array(str, dtype = 'str')
print(numpy_array_str)


# In a similar manner, other data-types can also be used to create a Numpy array.

[ 1.  8.  5. 59.  8. 98.]
['the' 'air' 'after' 'summer' 'rain']


A short documentation about the `np.array` function can be found by doing `np.array?`

In [40]:
#np.array?  # Uncomment to run the cell.

### NumPy Arrays using the function arange()

The `arange()` function is one of the Numpy's most used method for creating an array within a specified range. The first argument takes the **starting point** of the array you want to create, second is the **stop point** and the third is the **step** (just like python list slicing function). The last argument is again *dtype*, which is optional: `arange(start, end, step, dtype)`

In [41]:
# creating an array starting from 0 ending with 10 
# and increasing with a step of 2
arange_array1 = np.arange(0,11,2)   # writing 11 instead of 10 since range is exclusive
print("First array:", arange_array1)
print("======================================")


# array starting from 50 going till 120 with step of 4
arange_array2 = np.arange(50,121,4)
print("Second Array:", arange_array2)
print("======================================")


# starting from 0(by default), stopping at 14(don't forget 15 is exclusive), step=1(by default)
arange_array3 = np.arange(15) 
print("Third Array:", arange_array3)
print("======================================")


# okay now lets print backward counting: 20 to 1
arange_array4 = np.arange(20,0,-1)
print("Reverse Array:", arange_array4)


First array: [ 0  2  4  6  8 10]
Second Array: [ 50  54  58  62  66  70  74  78  82  86  90  94  98 102 106 110 114 118]
Third Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Reverse Array: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


### NumPy Arrays using the function linspace()

Like the `arange()` function, the `linspace()` function can also be used to create Numpy array. In the `arange()` function, we had control over where to start the Numpy array from, where to stop and step points but with `linspace()` we can maintain a proper linear stepping or spacing between array elements value while generating the array. The `linspace()` function takes arguments: **start index**, **end index** and the **number of elements** to be outputted. These number of elements would be linearly spaced in the range mentioned: `linspace(start_index, end_index, num_of_elements)`. Now let's take a code example,


In [42]:
# printing arr consisting of 10 values in between 
# range 15, 75 spaced appropriately.
arr = np.linspace(15, 75, 10)     
print("First Array\n", arr)

print("=========================================================")

# properly spaced array of 25 elements
arr1 = np.linspace(50,100,25)   
print("Second Array\n", arr1)

First Array
 [15.         21.66666667 28.33333333 35.         41.66666667 48.33333333
 55.         61.66666667 68.33333333 75.        ]
Second Array
 [ 50.          52.08333333  54.16666667  56.25        58.33333333
  60.41666667  62.5         64.58333333  66.66666667  68.75
  70.83333333  72.91666667  75.          77.08333333  79.16666667
  81.25        83.33333333  85.41666667  87.5         89.58333333
  91.66666667  93.75        95.83333333  97.91666667 100.        ]


### NumPy Array Attributes

Before we continue in showing other ways of generating Numpy arrays, let's discuss some useful array attributes. We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [43]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes `ndim` (the number of dimensions), `shape` (the size of each dimension), and `size` (the total size of the array):

In [44]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the `dtype`, the data type of the array (which we already discussed).

In [45]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [46]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

#### Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [47]:
x1

array([5, 0, 3, 3, 7, 9])

In [48]:
print(x1[0])
print("-----------")


print(x1[4])
print("-----------")

    
    

print(x1[-1])
print("-----------")


    
    
    
print(x1[-2])
print("-----------")

    

5
-----------
7
-----------
9
-----------
7
-----------


In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [49]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [50]:
print(x2[0,0])
print("-----------")


print(x2[2,0])
print("-----------")

    
    

print(x2[2,-1])
print("-----------")


    
    
    
print(x2[-2])
print("-----------")

3
-----------
1
-----------
7
-----------
[7 6 8 8]
-----------


Values can also be modified using any of the above index notation:

In [51]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [52]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

#### Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

##### One-dimensional subarrays

In [53]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [55]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [56]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [57]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [58]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [59]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [60]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

##### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [61]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [62]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [63]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [64]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [65]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [66]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [67]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


#### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [68]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let's extract a $2 \times 2$ subarray from this:

In [69]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [70]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [71]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

#### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [72]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [73]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [74]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


#### Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [75]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [76]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [77]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [78]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [79]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Some Numpy Special Arrays

#### Numpy Zeros: numpy.zeros()

Numpy zeros function returns a numpy array of only zeros with specified shape and data type.
Syntax

                                zeros(shape, dtype=float, order='C')
                         
   1. shape – This is the shape of the required array, input has to be an int or a tuple of int.
   2. dtype (optional) – This is the required data type of the array, by default it is float.
   3. order (optional) – This specifies how the array will be stored in the memory. It can be either ‘C’ for row-major or ‘F’ for column-major. By default, it is ‘C’.
                      

In [80]:

# Notice that we did not specify the data type, so by default, it assumed float.
# 1-D Array
np_1d_zero_array = np.zeros(4)

print('Output- ')
print(np_1d_zero_array)
print('Shape- ', np_1d_zero_array.shape)
print('Data type -', np_1d_zero_array.dtype)



print("======================================================")


# 2-D Array
np_2d_zero_array = np.zeros((4,2))

print('Output- ')
print(np_2d_zero_array)
print('Shape- ', np_2d_zero_array.shape)
print('Data type -', np_2d_zero_array.dtype)


print("======================================================")



# 3-D Array
np_3d_zero_array = np.zeros((4,2,3), int)

print('Output- ')
print(np_3d_zero_array)
print('Shape- ', np_3d_zero_array.shape)
print('Data type -', np_3d_zero_array.dtype)

Output- 
[0. 0. 0. 0.]
Shape-  (4,)
Data type - float64
Output- 
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Shape-  (4, 2)
Data type - float64
Output- 
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
Shape-  (4, 2, 3)
Data type - int64


#### Numpy Ones: numpy.ones()

This is very similar to Numpy Zero. Here Numpy zeros function returns a numpy array of only ones with specified shape and data type.

Syntax

                              ones(shape, dtype=float, order=’C’)

In [81]:
# 1-D Array
np_1d_ones_array = np.ones(4,int)

print('Output- ')
print(np_1d_ones_array)
print('Shape- ', np_1d_ones_array.shape)
print('Data type -', np_1d_ones_array.dtype)


print("======================================================")


# 2-D Array
np_2d_ones_array = np.ones((4,2))

print('Output- ')
print(np_2d_ones_array)
print('Shape- ', np_2d_ones_array.shape)
print('Data type -', np_2d_ones_array.dtype)




# 3-D Array
np_3d_ones_array = np.ones((4,2,3))

print('Output- ')
print(np_3d_ones_array)
print('Shape- ', np_3d_ones_array.shape)
print('Data type -', np_3d_ones_array.dtype)

Output- 
[1 1 1 1]
Shape-  (4,)
Data type - int64
Output- 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Shape-  (4, 2)
Data type - float64
Output- 
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
Shape-  (4, 2, 3)
Data type - float64


#### Numpy Eye: numpy.eye()

Numpy eye function helps to create a 2-D array where the diagonal has all ones and zeros elsewhere.
Syntax

                            eye(N, M=None, k=0, dtype='float', order='C')
                            
   1. N – It is the number of rows in the array. It has to be int.
   2. M (optional) – It is the number of columns in the array. If not specified then it will default to N.
   3. K (optional) – It denotes the position of diagonal ones. By default is zero i.e. in middle. A positive value denotes upper diagonal and negative value lower diagonal.
   4. dtype (optional) – This is the required data type of the array, by default it is float.
   5. order (optional) – This specifies how the array will be stored in the memory. It can be either ‘C’ for row-major or ‘F’ for column-major. By default, it is ‘C’.                       

In [82]:
np_identity_matrix_oder_4 = np.eye(4)

print('Output- ')
print(np_identity_matrix_oder_4)
print('Shape- ', np_identity_matrix_oder_4.shape)
print('Data type -', np_identity_matrix_oder_4.dtype)

Output- 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape-  (4, 4)
Data type - float64


##### Miscellaneous Examples of Numpy Eye

In [83]:

np.eye(4, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [84]:
np.eye(4, 5, k = 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### NumPy Arrays using the function empty()

The `empty()` function is used to create arrays when we don't really have any values to create an array. What it does is, it takes the shape of the array as desired and the array is then filled with random values. The trick here is that without even using the random module we are able to build an array full of random values: `empty(shape, dtype)`

In [85]:
# arr of shape (5,2) with datatype=float filled with random values
empty_arr = np.empty((5,2), dtype=float) 
print("Array with Float values\n", empty_arr)
print("======================================")



# observe what happens when executed
empty_arr1 = np.empty((4,4), dtype=int) 
print("Second Array \n", empty_arr1)

Array with Float values
 [[15.         21.66666667]
 [28.33333333 35.        ]
 [41.66666667 48.33333333]
 [55.         61.66666667]
 [68.33333333 75.        ]]
Second Array 
 [[4607182418800017408                   0                   0
                    0]
 [                  0 4607182418800017408                   0
                    0]
 [                  0                   0 4607182418800017408
                    0]
 [                  0                   0                   0
  4607182418800017408]]


## Operations on Arrays

### Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

#### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [86]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))

print("========================================")

# You can also concatenate more than two arrays at once:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))
print("========================================")



#It can also be used for two-dimensional arrays:
grid = np.array([[1, 2, 3],[4, 5, 6]])

# concatenate along the first axis
print(np.concatenate([grid, grid]))
print("========================================")


# concatenate along the second axis (zero-indexed)
print(np.concatenate([grid, grid], axis=1))

[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [87]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [88]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [89]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [90]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [92]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, ``np.dsplit`` will split arrays along the third axis.

### Numpy Arrays Universal Functions 

Computation on NumPy arrays can be very fast, or it can be very slow.
The key to making it fast is to use *vectorized* operations, generally implemented through NumPy's *universal functions* (ufuncs).
This section motivates the need for NumPy's ufuncs, which can be used to make repeated calculations on array elements much more efficient.
It then introduces many of the most common and useful arithmetic ufuncs available in the NumPy package.

#### Array arithmetic

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators.
The standard addition, subtraction, multiplication, and division can all be used:

In [93]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [94]:
# There is also a unary ufunc for negation, 
# and a ``**`` operator for exponentiation, 
# and a ``%`` operator for modulus

print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [95]:
# In addition, these can be strung together however you wish,
# and the standard order of operations is respected:

-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [96]:
#Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy; 
# for example, the ``+`` operator is a wrapper for the ``add`` function
np.add(x, 2)

array([2, 3, 4, 5])

The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

Additionally there are Boolean/bitwise operators; we will explore these in [Comparisons, Masks, and Boolean Logic]().

#### Absolute value

Just as NumPy understands Python's built-in arithmetic operators, it also understands Python's built-in absolute value function:

In [97]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [98]:
# The corresponding NumPy ufunc is ``np.absolute``, which is also available under the alias ``np.abs``:

In [99]:
print(np.absolute(x))

print("===============================")


print(np.absolute(x))

[2 1 0 1 2]
[2 1 0 1 2]


In [100]:
# This ufunc can also handle complex data, in which the absolute value returns the magnitude:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

#### Trigonometric functions

NumPy provides a large number of useful ufuncs, and some of the most useful for the data scientist are the trigonometric functions.
We'll start by defining an array of angles:

In [101]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [102]:
# The values are computed to within machine precision, which is why values 
# that should be zero do not always hit exactly zero. 
#Inverse trigonometric functions are also available:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


#### Exponents and logarithms

Another common type of operation available in a NumPy ufunc are the exponentials:

In [103]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


The inverse of the exponentials, the logarithms, are also available.
The basic ``np.log`` gives the natural logarithm; if you prefer to compute the base-2 logarithm or the base-10 logarithm, these are available as well:

In [104]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


#### Ufuncs: Learning More

More information on universal functions (including the full list of available functions) can be found on the [NumPy](http://www.numpy.org) and [SciPy](http://www.scipy.org) documentation websites.

Recall that you can also access information directly from within IPython by importing the packages and using IPython's tab-completion and help (``?``) functionality